version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6864
      POSTGRES_DB: new_test_db
    networks:
      - app_network
    ports:
      - "5432:5432"

networks:
  app_network:
    driver: bridge
